# Generated by Django 5.1 on 2025-07-22 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('cnic', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField(null=True)),
                ('patient_gender', models.CharField(max_length=11)),
                ('patient_photo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('patient_status', models.CharField(max_length=20, null=True)),
                ('patient_diagnosis', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_phone', models.IntegerField(null=True)),
                ('patient_email', models.CharField(max_length=100, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_panel_api.patientinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent_visit_date', models.DateField()),
                ('next_visit_date', models.DateField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_panel_api.patientinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PatientLabReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_report', models.FileField(upload_to='documents')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_panel_api.patientinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=100, null=True)),
                ('medication_dosage', models.IntegerField()),
                ('medication_frequency', models.IntegerField(null=True)),
                ('medication_timing', models.CharField(max_length=50, null=True)),
                ('medication_start_time', models.DateField()),
                ('medication_end_time', models.DateField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_panel_api.patientinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_tempreture', models.IntegerField(null=True)),
                ('patient_blood_pressure', models.IntegerField(null=True)),
                ('patient_glucose_level', models.IntegerField(null=True)),
                ('patient_weight', models.IntegerField(null=True)),
                ('patient_stress', models.CharField(max_length=20)),
                ('patient_oxygen', models.CharField(max_length=30)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_panel_api.patientinfo')),
            ],
        ),
    ]
